POST http://localhost:8080/login
Content-Type: application/json

{"user" : "samsad" , "password": "123"}

>{%
client.assert(typeof response.body.token !== "undefined", "No token returend");
client.global.set("auth_token",response.body.token);
  %}

